---
defaults:
  - _self_
  - transforms/test_transform@data_transform

checkpoint_path: ${oc.env:DATADIR}/image_classification/training_runs/2024-01-03_19-15-17/image-classification-transformer/xdf6g7p3/checkpoints/epoch=0-val_accuracy=0.50.ckpt
input_image_path: ${oc.env:DATADIR}/image_classification/datasets/cats_vs_dogs/train/cat.12496.jpg
attention_viz_outdir: ${oc.env:DATADIR}/image_classification/datasets/cats_vs_dogs/custom_test/results/
