---
defaults:
  - _self_
  - model/resnet
  - transforms/train_transform@dataset_factory.config.train_transform
  - transforms/test_transform@dataset_factory.config.val_transform

dataset_factory:
  _target_: image_classification.data.dataset.create_train_val_datasets
  config:
    root_dir:
      _target_: pathlib.Path
      _args_:
        - ${oc.env:DATADIR}/image_classification/datasets/cats_vs_dogs
    train_val_ratio: 0.8
    tiny_dataset: false
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.00001
lr_scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  patience: 20
  verbose: true
  factor: 0.1
  mode: min
  min_lr: 1e-6
batch_size: 2
num_epochs: 100
num_dataloader_workers: 4
output_dir: ${oc.env:DATADIR}/image_classification/training_runs
lightning_callbacks:
  - _target_: lightning.pytorch.callbacks.ModelCheckpoint
    monitor: val_accuracy
    mode: max
    save_top_k: 3
    filename: '{epoch}-{val_accuracy:.2f}'
  - _target_: lightning.pytorch.callbacks.early_stopping.EarlyStopping
    monitor: val_loss
    patience: 40
    mode: min
    verbose: true
wandb_enabled: true
