---
dataset_params:
  batch_size: 2
  train_to_val_ratio: 0.8
  num_workers: 8
model:
  _target_: sentiment_classification.models.text_transformer.TransformerForClassification
  params:
    emb_dim: 256
    n_heads: 8
    hid_dim: 512
    n_layers: 8
    output_dim: 1
    dropout: 0.1
    max_seq_length: 5000
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.00005
lr_scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  patience: 3
  verbose: true
  factor: 0.32
  mode: min
  min_lr: 1e-6
num_epochs: 100
save_top_k_models: 3
early_stopping_patience: 10

output_dir: ${oc.env:DATADIR}/sentiment_classification/training_runs
wandb_enabled: true
