project: sentiment-classification-transformer
program: sentiment_classification.train
method: random
run_cap: 15
metric:
  name: val_accuracy
  goal: maximize
parameters:
  # dataset_params.batch_size:
  #   values: [2, 4, 8]
  # model.params.n_heads:
  #   values: [4, 6, 8]
  # model.params.hid_dim:
  #   values: [256, 512, 1024]
  model.params.n_layers:
    values: [8, 12, 16]
  model.params.dropout:
    min: 0.1
    max: 0.35
  # optimizer.lr:
  #   min: 0.00001
  #   max: 0.0001

command:
  - ${env}
  - python
  - -m
  - ${program}
  - ${args_no_hyphens}
